"""Generate Millet's MLB without compiling or writing into the Rune checkout."""
import json
import os
from sml_sources import root, service_sources, compiler_sources

build = root / 'build'
build.mkdir(exist_ok=True)
groups = [service_sources(), compiler_sources(),
          [root / 'examples/hello/greeting.sml', root / 'examples/hello/main.sml']]
lines = ['(* Generated by scripts/gen-build-files.py; do not edit. *)']
for sources in groups:
    # Each executable has its own scope, including its Basis and entry point.
    lines.extend(['local', '  $(SML_LIB)/basis/basis.mlb'])
    for source in sources:
        if not source.is_file():
            raise SystemExit(f'Missing SML input: {source}')
        lines.append('  ' + json.dumps(os.path.relpath(source, build), ensure_ascii=False))
    lines.extend(['in', 'end'])
(build / 'ide.mlb').write_text('\n'.join(lines) + '\n')
print('Generated build/ide.mlb for Millet')
